services:
  cloudflared:
    build:
      context: cloudflared
      dockerfile: ./Dockerfile

  badguy-music-discordbot:
    build:
      context: BadGuy-Music-DiscordBot
      dockerfile: ./Dockerfile
    volumes:
      - cookies.txt:/App/databases/cookies.txt
