services:
  cloudflared:
    build:
      context: cloudflared
      dockerfile: ./Dockerfile

  badguy-music-discordbot:
    build:
      context: BadGuy-Music-DiscordBot
      dockerfile: ./Dockerfile

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
