#!/bin/bash

# turn on bash's job control
set -m

# Start the primary process and put it in the background
tmux new-session -s CF -d
tmux send -t CF 'cloudflared tunnel --no-autoupdate run --token $1' ENTER

# Start the helper process
/usr/sbin/sshd -D

# the my_helper_process might need to know how to wait on the
# primary process to start before it does its work and returns
tmux new-session -s App -d 
tmux send -t App 'cd /App' ENTER
tmux send -t App 'sudo python3 main.py' ENTER

# now we bring the primary process back into the foreground
# and leave it there
tmux attach-session -t CF
