name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: docker build --build-arg "TOKEN=${{ secrets.TOKEN }}" -t test .
      - name: Run
        run: docker run -it --name=test test 
          
