name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . --file Dockerfile --build-arg "TOKEN=${{ secrets.TOKEN }}" -t test
      - name: Run
        run: docker run -it --name=test test 
          
