name: ci

on:
  push:
    branches:
      - "BadGuy-Music-DiscordBot"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker compose build --build-arg "CF_TOKEN=${{ secrets.TOKEN }}" --build-arg "DC_TOKEN=${{ secrets.DC_TOKEN }}" --build-arg "SPF_CID=${{ secrets.SPF_CID }}" --build-arg "SPF_SECRET=${{ secrets.SPF_SECRET }}"
      - name: Run
        run: docker compose up
