name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker compose build --build-arg "CF_TOKEN=${{ secrets.TOKEN }}"
      - name: Run
        run: docker compose up
